name: Medixbot Static Application
'on':
  push:
    branches: master
jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List output files
        run: find -print

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: '*'
          target: ${{ secrets.TARGET_DIR }}
          strip_components: 1
          overwrite: true
